spring:
  kafka:
    # Kafka ?? ??
    bootstrap-servers: 3.37.130.149:9092
    producer:
      # ???? key ??? ?? : ?? ??? ???(String)? ???? Kafka? ??
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # ???? value ??? ?? : ?? ??? ???(String)? ???? Kafka? ??
      value-serializer: org.apache.kafka.common.serialization.StringSerializer