server:
  port: 0 # ?? ??? ?? ??? ??? ??? ?? (Producer ???? ?? ??? ??)

spring:
  kafka:
    # Kafka ?? ?? (EC2? ???? ???? ??? EC2 ??? ???? ??.)
    bootstrap-servers: 3.37.130.149:9092
    consumer:
      # ???? key ???? ?? : Kafka?? ??? ???? String?? ??
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ???? value ???? ?? : Kafka?? ??? ???? String?? ??
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # ??? ??? ?? ? ?????? ???, ??? ??? ?? ???? ???? ???? ??.
      # ?? ??? ??? ?? ???????, ?? ??? ??? ??? ????? ??.

      # ? ??? ?? ??? ??? ??? ?? ???? ???? ?? ?,
      # ??? ???? ???? ?? ?? ??? ??? ??? ??? ??? ????? ?????.
      # ?? ??? ??? ???? ?? ???? ????? ???? ?? ??????.
      auto-offset-reset: earliest
